### ISSUE TITLE
Upload files only

### ISSUE THREAD

**Issue by tphalp** [kbremner/grunt-dropbox#11]
I'm trying to upload only the files in a directory, and not the directory structure itself. I have only been able to upload the entire directory, using the example in the readme as a base.

Thanks for any help.

**Comment by bambooCZ** [comment]
+1

**Comment by kbremner** [comment]
Sorry for not replying, I completely forget that you had replied. I know it's been a while but could you show me the options your providing?

**Comment by bambooCZ** [comment]
```JavaScript

        dropbox: {
            options: {
                access_token: 'XXX',
            },
            macDmg: {
                files: [{
                    expand: false,
                    flatten: true,
                    cwd: ".",
                    src: ["builds/**/*.dmg"],
                    dest: "Browser/MAC"
                }]
            }
        }

```

I want to make Grunt to upload file into 'Browser/MAC/release.dmg' , but it is still uploading to 'Browser/MAC/release.dmg/builds/whatever/release.dmg'

Solved by replacing 'filepath' with 'filename' in file 'tasks/dropbox.js', line 50

**Comment by kbremner** [comment]
Thanks, just noticed the typo, cheers!

**Comment by bambooCZ** [comment]
thx
